// Code generated by go-swagger; DO NOT EDIT.

package o_auth2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AuthorizeOKCode is the HTTP code returned for type AuthorizeOK
const AuthorizeOKCode int = 200

/*AuthorizeOK The authorization page

swagger:response authorizeOK
*/
type AuthorizeOK struct {
}

// NewAuthorizeOK creates AuthorizeOK with default headers values
func NewAuthorizeOK() *AuthorizeOK {

	return &AuthorizeOK{}
}

// WriteResponse to the client
func (o *AuthorizeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
