// Code generated by go-swagger; DO NOT EDIT.

package o_auth2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AuthenticateOKCode is the HTTP code returned for type AuthenticateOK
const AuthenticateOKCode int = 200

/*AuthenticateOK The authentication page.

swagger:response authenticateOK
*/
type AuthenticateOK struct {
}

// NewAuthenticateOK creates AuthenticateOK with default headers values
func NewAuthenticateOK() *AuthenticateOK {

	return &AuthenticateOK{}
}

// WriteResponse to the client
func (o *AuthenticateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AuthenticateFoundCode is the HTTP code returned for type AuthenticateFound
const AuthenticateFoundCode int = 302

/*AuthenticateFound Redirect to the given redirect_uri if the parameter validation failed.

swagger:response authenticateFound
*/
type AuthenticateFound struct {
}

// NewAuthenticateFound creates AuthenticateFound with default headers values
func NewAuthenticateFound() *AuthenticateFound {

	return &AuthenticateFound{}
}

// WriteResponse to the client
func (o *AuthenticateFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}
