// Code generated by go-swagger; DO NOT EDIT.

package o_auth2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// AuthenticateURL generates an URL for the authenticate operation
type AuthenticateURL struct {
	ClientID     string
	RedirectURI  string
	ResponseType string
	Scope        *string
	State        string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *AuthenticateURL) WithBasePath(bp string) *AuthenticateURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *AuthenticateURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *AuthenticateURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/authenticate"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	clientIDQ := o.ClientID
	if clientIDQ != "" {
		qs.Set("client_id", clientIDQ)
	}

	redirectURIQ := o.RedirectURI
	if redirectURIQ != "" {
		qs.Set("redirect_uri", redirectURIQ)
	}

	responseTypeQ := o.ResponseType
	if responseTypeQ != "" {
		qs.Set("response_type", responseTypeQ)
	}

	var scopeQ string
	if o.Scope != nil {
		scopeQ = *o.Scope
	}
	if scopeQ != "" {
		qs.Set("scope", scopeQ)
	}

	stateQ := o.State
	if stateQ != "" {
		qs.Set("state", stateQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *AuthenticateURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *AuthenticateURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *AuthenticateURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on AuthenticateURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on AuthenticateURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *AuthenticateURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
