// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Zerberus
//
//  This is the public API of the Zerberus authorization server.
//  Terms Of Service:
//    TBD
//  Schemes:
//    http
//  Host: TBD
//  BasePath: /v1
//  Version: 0.1.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <eldelto77@gmail.com>
//
//  Consumes:
//    - application/x-www-form-urlencoded
//
//  Produces:
//    - text/html
//    - application/json
//
// swagger:meta
package restapi
