// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is the public API of the Zerberus authorization server.",
    "title": "Zerberus",
    "termsOfService": "TBD",
    "contact": {
      "email": "eldelto77@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.1.0"
  },
  "host": "TBD",
  "basePath": "/v1",
  "paths": {
    "/oauth2/login": {
      "get": {
        "produces": [
          "text/html"
        ],
        "tags": [
          "pet"
        ],
        "summary": "Add a new pet to the store",
        "operationId": "addPet",
        "parameters": [
          {
            "type": "string",
            "description": "The expected response type (currently only code is supported)",
            "name": "response_type",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The login page"
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your Pets",
      "name": "pet",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    },
    {
      "description": "Access to Petstore orders",
      "name": "store"
    },
    {
      "description": "Operations about user",
      "name": "user",
      "externalDocs": {
        "description": "Find out more about our store",
        "url": "http://swagger.io"
      }
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is the public API of the Zerberus authorization server.",
    "title": "Zerberus",
    "termsOfService": "TBD",
    "contact": {
      "email": "eldelto77@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.1.0"
  },
  "host": "TBD",
  "basePath": "/v1",
  "paths": {
    "/oauth2/login": {
      "get": {
        "produces": [
          "text/html"
        ],
        "tags": [
          "pet"
        ],
        "summary": "Add a new pet to the store",
        "operationId": "addPet",
        "parameters": [
          {
            "type": "string",
            "description": "The expected response type (currently only code is supported)",
            "name": "response_type",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The login page"
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your Pets",
      "name": "pet",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    },
    {
      "description": "Access to Petstore orders",
      "name": "store"
    },
    {
      "description": "Operations about user",
      "name": "user",
      "externalDocs": {
        "description": "Find out more about our store",
        "url": "http://swagger.io"
      }
    }
  ]
}`))
}
