// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewAddPetParams creates a new AddPetParams object
// no default values defined in spec.
func NewAddPetParams() AddPetParams {

	return AddPetParams{}
}

// AddPetParams contains all the bound params for the add pet operation
// typically these are obtained from a http.Request
//
// swagger:parameters addPet
type AddPetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The expected response type (currently only code is supported)
	  Required: true
	  In: query
	*/
	ResponseType string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddPetParams() beforehand.
func (o *AddPetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qResponseType, qhkResponseType, _ := qs.GetOK("response_type")
	if err := o.bindResponseType(qResponseType, qhkResponseType, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindResponseType binds and validates parameter ResponseType from query.
func (o *AddPetParams) bindResponseType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("response_type", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("response_type", "query", raw); err != nil {
		return err
	}

	o.ResponseType = raw

	return nil
}
