// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddPetOKCode is the HTTP code returned for type AddPetOK
const AddPetOKCode int = 200

/*AddPetOK The login page

swagger:response addPetOK
*/
type AddPetOK struct {
}

// NewAddPetOK creates AddPetOK with default headers values
func NewAddPetOK() *AddPetOK {

	return &AddPetOK{}
}

// WriteResponse to the client
func (o *AddPetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
